# Application Configuration
server:
  port: 8081


spring:
  application:
    name: learning-management-system

# DataSource Configuration
datasource:
  url: jdbc:h2:mem:testdb
  driver-class-name: org.h2.Driver
  username: sa
  password: password
  initialization-mode: always

# JPA Configuration
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true

# H2 Console Configuration (Optional, for database visualization)
h2:
  console:
    enabled: true
    path: /h2-console
